### ISSUE TITLE
combination model

### ISSUE THREAD

**Issue by DelphIONe** [comprna/METEORE#13]
What is the interest of use an trained combination model ? What is the difference or benefit in comparison with your combination model (already trained) ? 
And the same question between default model or optimized model for the combination ? I searched in your documentation but I didn't find any explanations.

Thanks,

**Comment by zakayuen** [comment]
Thank you for using our tool. Please have a look at our preprint where you will find the detailed explanations: [https://www.biorxiv.org/content/10.1101/2020.10.14.340315v5](url). Here, we performed benchmarking of these methylation tools.

A consensus model may capture the advantages of the individual methods and compensate for their potential deficiencies because there are differences in the accuracy between different individual methods. We trained our model using _E.coli_ data and it showed that the consensus approach provided overall an increase in accuracy compared to individual methods.

Also, we used these parameters of the random forest (RF) classifier from the Python sklearn library: `max_dep=3 and n_estimator=10 `(optimized parameter). As for the default model, we used `n_estimator = 100 and max_dep = None` which are the default parameters. 

Thanks,
Zaka
